name: Build

on: workflow_dispatch

jobs:
  build_and_test:

    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
  
  
      - name: Build
        run: msbuild cvar-unhide-s2.sln /p:Configuration=Debug
  
  
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            *
